SSH:
  description: Generate SSH public and secret keys.
  input:
    KEY_LENGTH:
      name: key size (bits)
      type: combobox
      option:
        - 2048
        - 4096
    TYPE:
      name: type
      type: combobox
      option:
        - rsa
        - dsa
    button:
      name: Generate
      type: button
      actions: 
        - ssh-keygen -b $KEY_LENGTH -t $TYPE -f id_rsa -N ''
  output:
    PUBLIC_KEY:
      name: public key
      type: textarea
      content: id_rsa.pub
    PRIVATE_KEY:
      name: private key
      type: textarea
      content: id_rsa
APG:
  description: Automated Password Generator
  input:
    MIN_PASS_LEN:
      name: minimum password length
      type: number
      min: 8
      max: 20
    button:
      name: Generate
      type: button
      actions:
        - apg -M SNCL -m $MIN_PASS_LEN > temp
  output:
    LIST:
      name: random password
      type: textarea
      content: temp