services:
  ssh:
    service: ssh
    description: Generate SSH public and secret keys.
    cmd: ssh-keygen -f id_rsa -N '' 
    input:
      requires:
        - aaa
      options:
        - bbb
      button:
        name: Generate
        action: /ssh
        methon: post
    output:
      - {"title":"Private Key", "type":"textarea"}
      - {"title":"Public Key", "type":"textarea"}
