SSH:
  description: Generate SSH public and secret keys.
  input:
    KEY_LENGTH:
      name: key size (bits)
      type: combobox
      option:
        - 2048
        - 4096
    TYPE:
      name: type
      type: radio
      option:
        - rsa
        - dsa
    button:
      name: Generate
      type: button
      actions: 
        - ssh-keygen -b $KEY_LENGTH -t $TYPE -f id_rsa -N ''
  output:
    result:
      name: result
      type: textarea
      content:
        - id_rsa
        - id_rsa.pub
        - id_rsaa
        - id_rsaa.pub