ssh:
  description: Generate SSH public and secret keys.
  input:
    key size (bits):
      tag: select
      option:
        - 2048
        - 4096
    button:
      tag: button
      type: submit
      name: Generate
      action: ssh-keygen -b $KEY_LENGTH -f id_rsa.pub -N ''  
  output:
    result:
      tag: textarea
